/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types for Cloudflare Workers

declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker/index");
  }
  interface Env {
    // Add your environment variables here
    NODE_ENV?: string;
    // Example: SUPABASE_URL?: string;
    // Example: SUPABASE_SERVICE_ROLE_KEY?: string;
  }
}

interface Env extends Cloudflare.Env {}

// Cloudflare Workers runtime types
interface ExecutionContext {
  waitUntil(promise: Promise<any>): void;
  passThroughOnException(): void;
  readonly props: unknown;
}

type ExportedHandlerFetchHandler<Env = unknown> = (
  request: Request,
  env: Env,
  ctx: ExecutionContext
) => Response | Promise<Response>;

interface ExportedHandler<Env = unknown> {
  fetch?: ExportedHandlerFetchHandler<Env>;
}
