// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL: string =
  import.meta.env.VITE_SUPABASE_URL ||
  (import.meta.env.VITE_SUPABASE_PROJECT_ID
    ? `https://${import.meta.env.VITE_SUPABASE_PROJECT_ID}.supabase.co`
    : "");

const SUPABASE_PUBLISHABLE_KEY: string =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is missing from .env. Supabase client will fail to initialize."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ---- Tunables ----
// 6s per attempt × 2 attempts = 12s worst case for a single query. Pairs with
// React Query's retry:0 in App.tsx so the user sees a real error fast instead
// of waiting minutes for "data to load".
const REQUEST_TIMEOUT_MS = 6_000;
const PRIMARY_RETRIES = 1;
const BACKOFF_BASE_MS = 250;

// ---- Helpers ----
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const isRetryableStatus = (status: number) =>
  status === 408 || status === 425 || status === 429 || status >= 500;

const withTimeout = async (
  input: RequestInfo | URL,
  init: RequestInit | undefined,
  ms: number
) => {
  const ctrl = new AbortController();
  const callerSignal = init?.signal;
  if (callerSignal) {
    if (callerSignal.aborted) ctrl.abort(callerSignal.reason);
    else
      callerSignal.addEventListener(
        'abort',
        () => ctrl.abort(callerSignal.reason),
        { once: true }
      );
  }
  const timer = setTimeout(() => ctrl.abort(new Error('Request timeout')), ms);
  try {
    return await fetch(input, { ...init, signal: ctrl.signal });
  } finally {
    clearTimeout(timer);
  }
};

const attemptFetch = async (
  input: RequestInfo | URL,
  init: RequestInit | undefined,
  retries: number,
  label: string
): Promise<Response> => {
  let lastErr: unknown;
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const res = await withTimeout(input, init, REQUEST_TIMEOUT_MS);
      if (res.ok) return res;
      if (!isRetryableStatus(res.status) || attempt === retries) return res;
      lastErr = new Error(`${label} returned ${res.status}`);
    } catch (err) {
      lastErr = err;
      if (attempt === retries) break;
    }
    const delay = BACKOFF_BASE_MS * Math.pow(2, attempt) + Math.random() * 100;
    await sleep(delay);
  }
  throw lastErr instanceof Error ? lastErr : new Error(`${label} failed`);
};

// ---- Custom fetch with 401 recovery ----
// When the server returns 401 from a non-auth request, we know the stored
// session is no longer accepted by Supabase. We clear it so the next request
// forces a fresh sign-in. Without this, users hit a "stuck" state where every
// gated call returns 401 and the only fix is to manually clear site data.
const clearStaleSession = () => {
  try {
    const keys = Object.keys(localStorage);
    for (const key of keys) {
      // supabase-js stores session under sb-<project-ref>-auth-token (and a
      // few related keys). Clear them all.
      if (key.startsWith('sb-') && key.includes('-auth-')) {
        localStorage.removeItem(key);
      }
    }
  } catch {
    /* localStorage may be unavailable (SSR / sandboxed iframe) */
  }
};

const customFetch = async (
  input: RequestInfo | URL,
  init?: RequestInit
): Promise<Response> => {
  const urlStr = input.toString();
  const method = (init?.method || 'GET').toUpperCase();
  const isAuthRequest = urlStr.includes('/auth/v1/');

  try {
    const res = await attemptFetch(input, init, PRIMARY_RETRIES, 'Supabase');

    // Auth-gated request (anything other than /auth/v1/) returned 401 → the
    // stored session is rejected. Clear it so the next page load can sign in
    // fresh. Don't clear on /auth/v1/ itself (that's where the user is
    // actively trying to authenticate).
    if (
      !isAuthRequest &&
      (res.status === 401 || res.status === 403) &&
      method !== 'GET' // only auto-clear on failed writes; reads may just be RLS
    ) {
      clearStaleSession();
    }
    return res;
  } catch (err) {
    console.error('[Supabase] Request failed:', err);
    throw err;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Detect token refresh failures and clear the broken session so the user
    // can sign in again instead of being stuck in a half-authed state.
    detectSessionInUrl: true,
  },
  global: {
    fetch: customFetch,
  },
});

// React to sign-out events by clearing any related cached state. (Cached
// Supabase query data is held in React Query, which auto-drops on window
// unload; this just keeps localStorage clean.)
supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_OUT') {
    try {
      const keys = Object.keys(localStorage);
      for (const key of keys) {
        if (key.startsWith('sb-') && key.includes('-auth-')) {
          localStorage.removeItem(key);
        }
      }
    } catch {
      /* ignore */
    }
  }
});

let sharedSessionPromise: ReturnType<typeof supabase.auth.getSession> | null = null;

export const getSharedSession = () => {
  if (!sharedSessionPromise) {
    sharedSessionPromise = supabase.auth.getSession();
    setTimeout(() => {
      sharedSessionPromise = null;
    }, 2000);
  }
  return sharedSessionPromise;
};
