// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'dummy_key';

if (!SUPABASE_URL) {
  console.error("Supabase environment variables not configured");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const customFetch = async (input: RequestInfo | URL, init?: RequestInit) => {
  const urlStr = input.toString();
  
  try {
    const response = await fetch(input, init);
    // Failover on any non-ok response status (e.g. 401 key mismatch, 404 schema changes, 5xx)
    if (!response.ok) {
      throw new Error(`Primary database returned error status: ${response.status}`);
    }
    return response;
  } catch (error) {
    // If it's a network error or 5xx, try fallback
    const fallbackUrl = import.meta.env.VITE_SUPABASE_FALLBACK_URL;
    const fallbackKey = import.meta.env.VITE_SUPABASE_FALLBACK_KEY;
    const isPrimary = urlStr.startsWith(SUPABASE_URL);
    
    if (isPrimary && fallbackUrl && fallbackKey) {
      const method = init?.method || 'GET';
      // Option A: Block writes (Read-Only Fallback), except for Auth requests
      const isAuthRequest = urlStr.includes('/auth/v1/');
      if (!isAuthRequest && method !== 'GET' && method !== 'HEAD' && method !== 'OPTIONS') {
        throw new Error("System is in read-only maintenance mode. Please try saving later.");
      }

      console.warn('Falling back to secondary Supabase database...');
      const newUrl = urlStr.replace(SUPABASE_URL, fallbackUrl);
      
      const headers = new Headers(init?.headers);
      headers.set('apikey', fallbackKey);
      
      const authHeader = headers.get('Authorization');
      if (authHeader === `Bearer ${SUPABASE_PUBLISHABLE_KEY}`) {
        headers.set('Authorization', `Bearer ${fallbackKey}`);
      }

      return fetch(newUrl, { ...init, headers });
    }
    
    // Log the error to the console before throwing
    console.error(`[Supabase Fetch Error] Failed to fetch ${urlStr}:`, error);
    throw error;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customFetch
  }
});

let sharedSessionPromise: ReturnType<typeof supabase.auth.getSession> | null = null;

export const getSharedSession = () => {
  if (!sharedSessionPromise) {
    sharedSessionPromise = supabase.auth.getSession();
    // Clear the cached promise after a short delay so future calls fetch fresh data
    setTimeout(() => { sharedSessionPromise = null; }, 2000);
  }
  return sharedSessionPromise;
};